### ISSUE TITLE
Allow use of external dictionary

### ISSUE THREAD

**Issue by nemequ** [centaurean/density#10]
Right now, density adds (I believe) 16 bytes of header data to each block of compressed data.  For larger pieces of data this obviously isn't much of an issue and, while for most cases it's nice to have this information with each piece of data, there are applications where 16 bytes is a lot of data.

For example, one use case I'm interested in is compressing small pieces of data, such as rows (or cells) in a database, a blob of JSON/protobuf/thrift data, etc.  In such cases, it would be preferable to communicate everything you can out of band in order to reduce duplication.  In the case of a database, this information could be stored once per database instead of once per row/cell.  In other cases it could be hard-coded per application.

I don't think the stream API would be very useful for such use cases, but if there is a good way to expose a simple buffer API for this sort of thing, I think there could be a market for it.  I _think_ this would just require a simple function which just uses DENSITY_ENCODE_OUTPUT_TYPE_WITHOUT_HEADER_NOR_FOOTER, in which case I'll add codecs to Squash for this, but given how simple (I think) it is, I thought you might be interested in including it in density, too.

**Comment by gpnuma** [comment]
Available in 0.14.0
