### ISSUE TITLE
DENSITY_STREAM_MINIMUM_OUT_BUFFER_SIZE undefined

### ISSUE THREAD

**Issue by nemequ** [centaurean/density#12]
`DENSITY_STREAM_MINIMUM_OUT_BUFFER_SIZE` isn't defined when you only include `density_api.h'—it is in `stream.h`

**Comment by gpnuma** [comment]
Hey Evan thanks for your input. I'm currently working on a major update but I take your suggestion, I'll try to integrate this in the next release.

**Comment by gpnuma** [comment]
Fixed in ab5f1dd2a05b31f113c91b57afbe00f6486bbe41
