### ISSUE TITLE
macro or routine or algorithm to know maximum size of compressed block from input size.

### ISSUE THREAD

**Issue by mckellyln** [centaurean/density#48]
If there is a formula we could use for determining the maximum size of a compressed block based on its input size that would be of help for setting up buffers and/or when to call the compress function.  Most other compression packages have this feature and it can be a benefit.

**Comment by gpnuma** [comment]
Implemented in bf87ab2e8484de7ec260dd1d359fd19b9270e3b2 with density_buffer_compress_safe_size() and density_buffer_decompress_safe_size()
