### ISSUE TITLE
DENSITY_BUFFER_STATE_ERROR_DURING_PROCESSING

### ISSUE THREAD

**Issue by mckellyln** [centaurean/density#52]
I get this issue with all 3 algorithms with master, but do not get it with dev.
I will debug and try to provide details.
Can we get a master update soon ?

**Comment by gpnuma** [comment]
Hello Mark,
I haven't had much time these days to do any updating but I will in the next few weeks, and yes expect 0.13 to be pushed to master.

**Comment by neworldemancer** [comment]
I'm sometimes experiencing this error when decompressing if i set output buffer size equal to the uncompressed data size.
But it works fine if i set it bigger, rounded till nearest multiple of 256byte.
Is this real and enough requirement?
Does same one exist for compressing or only for decompressing?

**Comment by gpnuma** [comment]
Master updated to 0.14.0
