### ISSUE TITLE
Memory leak on decompression failure

### ISSUE THREAD

**Issue by nemequ** [centaurean/density#53]
I have some unit tests which intentionally causes the decoder to fail, and I have noticed that if the stream is left in some states (such as `STALL_ON_OUTPUT`) then there will be a memory leak even if I call `density_stream_decompress_finish`, since that function will only free memory from certain states.

Ideally, I don't think I should have to call `density_stream_decompress_finish`; `density_stream_destroy` should take care of everything.  If I want to abort decoding I should just be able to destroy the stream and be done with it, regardless of what state the stream is in.

I don't think you really need it, but here is a trace from asan:

```
Direct leak of 262200 byte(s) in 1 object(s) allocated from:
    #0 0x7ff61cf7ea0a in malloc (/lib64/libasan.so.2+0x98a0a)
    #1 0x7ff6186d9ae9 in density_decode_init /home/nemequ/local/src/squash/plugins/density/density/src/main_decode.c:84
    #2 0x7ff6186e0ceb in density_stream_decompress_init /home/nemequ/local/src/squash/plugins/density/density/src/stream.c:189
    #3 0x7ff6184e1d33 in squash_density_process_stream /home/nemequ/local/src/squash/plugins/density/squash-density.c:328
    #4 0x7ff61ccd20e3 in squash_stream_process_internal /home/nemequ/local/src/squash/squash/stream.c:608
    #5 0x7ff61ccd283a in squash_stream_process /home/nemequ/local/src/squash/squash/stream.c:718
    #6 0x7ff61cca956f in squash_codec_decompress_with_options /home/nemequ/local/src/squash/squash/codec.c:734
    #7 0x401cb3 in check_codec /home/nemequ/local/src/squash/tests/bounds.c:42
    #8 0x7ff61c777b92  (/lib64/libglib-2.0.so.0+0x6fb92)
```

**Comment by nemequ** [comment]
FWIW there doesn't need to be an error when decoding.  This also happens if the user stops processing a stream without processing the whole thing (for example, because they only want the first N bytes).

**Comment by elliotwoods** [comment]
I encountered this also.
I'm working with network streams, so often get broken messages (i.e. unfinished decompression streams).
Is there a way to fix this memory leak?

**Comment by gpnuma** [comment]
Unapplicable to 0.14.0
