### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by rdp** [centaurean/density#54]
might be nice to provide a mailing list so that we can have chats more easily.
Cheers!

**Comment by gpnuma** [comment]
Yes that's been an ongoing request ... any good ideas on free mailing list service providers ?

**Comment by rdp** [comment]
google group seems to be my go to these days.

**Comment by nemequ** [comment]
IMHO Google Groups is a good choice because it doubles as a web-based forum.  Most of the other places you can host mailing lists have read-only web interfaces.

**Comment by gpnuma** [comment]
Ok there it is : 
https://groups.google.com/d/forum/centaurean-density
Thanks

**Comment by rdp** [comment]
Awesome.

When I go there it says:

Centaurean Density
You must be a member of this group to view and participate in it.

Apply for membership or contact the owner
<https://groups.google.com/d/contactowner/centaurean-density>.
Report this group

you may want to make it a "public" group, as it were.
Thanks!

**Comment by gpnuma** [comment]
Thanks ! I changed it to public now.

**Comment by rdp** [comment]
may want to mention it in the README or website or what not :)
