### ISSUE TITLE
Crashes from fuzzing

### ISSUE THREAD

**Issue by nemequ** [centaurean/density#60]
m^2 [reported some issues on encode.ru](http://encode.ru/threads/1841-SHARC-DENSITY-news-and-updates?p=45468&viewfull=1#post45468) a while back (2015-11-03).

**Comment by nemequ** [comment]
Not sure if this the same issue or not, but http://code.coeusgroup.com/6245d327e3fd1243ebf996ad282d4343d0a863d8 causes density to crash when attempting to decode it.  It wasn't generated by a fuzzer, it was stumbled upon during a CI build (https://travis-ci.org/quixdb/squash/jobs/103533330#L3485) which anyone can reproduce, so the issue is already public.

**Comment by gpnuma** [comment]
Fixed in 0.14.0
