### ISSUE TITLE
densityxx is a C++ version of density

### ISSUE THREAD

**Issue by charlesw1234** [centaurean/density#61]
Can I have a link in the page of density?

https://github.com/charlesw1234/densityxx

**Comment by gpnuma** [comment]
Hello Charles,

First of all, congratulations for your work !
Of course, I’ll add your C++ port in the home page.
Hopefully I’ll be able to continue working on the library later this year, there are a few interesting things under progress in the dev branch.
Have a nice day !
Guillaume

**Comment by gpnuma** [comment]
Added a "related projects" section in the README

**Comment by charlesw1234** [comment]
thanks! I'm trying to use template to speed it up.
