### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by neworldemancer** [centaurean/density#62]
compilation fails with message 
`Linking benchmark
obj/Release/benchmark/benchmark.o : fatal error LNK1107: invalid or corrupt file: cannot read at 0x4B70
clang.exe: error: linker command failed with exit code 1107 (use -v to see invocation)
make[1]: *** [bin/Release/benchmark.exe] Fehler 83
make: *** [benchmark] Fehler 2`

**Comment by TheSHEEEP** [comment]
Same for me (well, almost):

> 
> obj/Release/benchmark/benchmark.o : fatal error LNK1107: invalid or corrupt file: cannot read at 0x4CD0
> clang.exe: error: linker command failed with exit code 1107 (use -v to see invocation)

**Comment by neworldemancer** [comment]
well, I did a workaround by editing the already generated makefiles, to make it compile, but i don't have experience with premake to generate them properly automatically.
the point is you need 
1)generate obj files: 
`LLC = llc 
OBJECTS2 := $(OBJECTS:%.o=%.obj)
and then for each file call 
`$(SILENT) $(LLC) -filetype obj "$@" -o "$(@:%.o=%.obj)" `
2)perform the linking for them by redefining LINKCMD
`LINKCMD = $(AR) -rcs "$@" $(OBJECTS2) `

If you need x86 build you can also easily do so by defining `PLATFORM = -target i386-pc-windows-msvc`.
Look my makefiles for details:

[spookyhash.make.txt](https://github.com/centaurean/density/files/279346/spookyhash.make.txt)
[density.make.txt](https://github.com/centaurean/density/files/279348/density.make.txt)
[benchmark.make.txt](https://github.com/centaurean/density/files/279347/benchmark.make.txt)

**Comment by gpnuma** [comment]
Clang on windows sometimes seems to generate files unreadable by the linker.
Best option in that case could be to use mingw64 with the latest gcc as in the appveyor build.

**Comment by gpnuma** [comment]
Fixed in 0.14.1
