### ISSUE TITLE
MSVC compiler port

### ISSUE THREAD

**Issue by sasmaster** [centaurean/density#64]
Hi.Very impressive lib,based on the benchmarks I have seen!
I have got a question.What should it take to port this codebase to Microsoft compiler?Besides some compiler specific changes ,are there any special preprocessor defs,( vectorization or asm code) one should be aware of when trying to build with a different compiler than Clang?

**Comment by gpnuma** [comment]
Hello !
I haven't tried to port to the msvc compiler honestly, but I suspect a number of arrangements will have to be made - especially on the preprocessor side as you said -, but the lib works fine on gcc/windows.
I think your best bet would be to try it out !
Guillaume

**Comment by gpnuma** [comment]
I'm fixing this issue for now, we'll see in the future if this needs to be reopened.

**Comment by gpnuma** [comment]
Fixed in 0.14.1
