### ISSUE TITLE
why don`t you make standalone binaries ?

### ISSUE THREAD

**Issue by trevor122** [centaurean/density#73]
for Average Joe like me it is mission impossible to make binary for mac os x or windows

**Comment by gpnuma** [comment]
Hello, binaries of what exactly ? You mean density's benchmark ? Because it's meant to be a library.

**Comment by trevor122** [comment]
good morning, no I would wish to release binaries executables as standalone archiver application, not library. I do not know how was perform density in benchmarks I saw, but speed was amazing.
 
 
Martin
______________________________________________________________
> Od: Guillaume Voirin <notifications@github.com>
> Komu: centaurean/density <density@noreply.github.com>
> Datum: 05.02.2018 00:03
> Předmět: Re: [centaurean/density] why don`t you make standalone binaries ?
>
Hello, binaries of what exactly ? You mean density's benchmark ? Because it's meant to be a library.

**Comment by gpnuma** [comment]
What you want is the sharc archiver then, it's a single thread archiver based on density which is distributed with binaries. For the time being it's not available though, it will as soon as I have time to build a version with the latest density library.
If you want to access an old archive of the project based on an old density beta version, look here : https://github.com/gpnuma/sharc. No binaries are provided though as this should not be used in a production environment.
sharc will be made available again at some point in the future, with distributed binaries.

**Comment by trevor122** [comment]
good afternoon, pls make binaries asap I want to try your archiver (if you have previous binaries from https://archive.is/o/rj8Px/www.centaurean.com/downloads/sharc/0.9.5-beta/sharc_win64.exe pls send me them)
 
thank you
 
martin
______________________________________________________________
> Od: Guillaume Voirin <notifications@github.com>
> Komu: centaurean/density <density@noreply.github.com>
> Datum: 06.02.2018 14:53
> Předmět: Re: [centaurean/density] why don`t you make standalone binaries ?
>
What you want is the sharc archiver then, it's a single thread archiver based on density which is distributed with binaries. For the time being it's not available though, it will as soon as I have time to build a version with the latest density library.
 If you want to access an old archive of the project based on an old density beta version, look here : https://github.com/gpnuma/sharc <https://github.com/gpnuma/sharc>. No binaries are provided though as this should not be used in a production environment.
 sharc will be made available again at some point in the future, with distributed binaries.

**Comment by gpnuma** [comment]
Hello, as you've added the issue to sharc I'm removing it from here.
